name: CI Pipeline
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install --no-interaction
      - name: Debug check black
	run: poetry run which black
      - name: Check code format
        run: black --check .
      - name: Run tests
        run: pytest pygraph.py
      - name: Generate docs
        run: pdoc --html pygraph -o html/