name: CI Pipeline
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install --no-interaction
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Install pre-commit hooks
        run: pre-commit install
      - name: Install dependencies
        run: poetry install --with dev
      - name: Check code format
        run: poetry run black --check .
      - name: Run tests
        run: poetry run pytest -r P --cov=pygraph
      - name: Generate docs
        run: poetry run pdoc --html pygraph -o html/